### ISSUE TITLE
Clean up the .AWS config file 

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/container-host-bag#11]
After downloading our proprietary containers, this file is not needed. Please clean this up to be safer.

**Comment by SolomonShorser-OICR** [comment]
Should be fixed in the next release

**Comment by denis-yuen** [comment]
Looks like this is now done https://github.com/ICGC-TCGA-PanCancer/container-host-bag/blob/develop/roles/containers/tasks/main.yml#L23
