### ISSUE TITLE
Cleanup extras and don't leave stuff in /tmp

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/container-host-bag#12]
Java is re-downloaded for workers when bringing them up from a snapshot because the /tmp does not survive reboot

**Comment by denis-yuen** [comment]
Additionally, the pancancer-reporting jar is deployed to the worker where it is not needed.

**Comment by SolomonShorser-OICR** [comment]
The java deb archive could be saved in `~/`, it's probably the simplest way to handle this.

**Comment by SolomonShorser-OICR** [comment]
See pull request: https://github.com/ICGC-TCGA-PanCancer/container-host-bag/pull/16

**Comment by denis-yuen** [comment]
Looks good
